package main

import "fmt"

func findTheDifference(s string, t string) byte {
	byts := []byte(s + t)
	x := byte(0)
	for _, c := range byts {
		x ^= c
	}
	return x
}

func main() {
	fmt.Println(findTheDifference("xpmssbwloowxibtwvhabflaoqgoyswznxepaoevvqohhamkucbcfsonazfnmcoqechnyigsbuvzrligprykurwahetwjmdknmearurflryhligaptsdqrlgapoyzocwwnavcsdiuqpbzmedzsvifcqzjjqqjshqmxczobymhwwiojfcvfjvaygupgacyvhnckmdasgspxoijltxebfspwlpjbzpoonalwujttowlsiagmcgfqwxoznuehztvuvpgzrvrjnybfcolufwgwsgmuxdqfgcisxgeibinqxacrtwznwvmxximhhhdehxrftpcczubiabgkbscrundidaqzcbmzpiqecfruiffzuajxjnnwipeivtswffizywisuvhkkcjwgxazntusebfbaawflsazleudgmhyzgfspyqmqanozvksrougiypcmiokgdhmkwyngmrynkekfjogjpgannxdtczvgxmatirlfcsphzouosyknxigetrpzudjaxcepvdfmqfyjpvxifntszpbzfkrlxgodjecpvtljolottyhaonpvatwhynicfusbrcnfhkpglaouhmljaavvguoiyiynpqykhaqsbbdroszpawpzgjtnzmqeiuvbwhyphrhqzbaqnnusbiopkzbsovqtykfioyurtqqnspkhnllmsvkgewpslshrambdokxhrelsehvvgitcwyrhivarxjagtsgfnhudizcbmvncgjfa", "wsxqlutrifhyejgmohyvlkjobelupizpgbgavnltzspgvmthdhioonnilqshpsvyejddnitnxrpmdvkudqhoajzupcxrwghhyhudsqrszojzwpcbontwdbfbqncysqzgoayjxbqkieamizzsoaqksqwjmjawwmkltcfzffruhaarhcexhenrgizwvnqfkrfhthbovxuynxoltrtagsceiiphsombaqcztfookpepwymnsxtlspgbdkmyezlzdvinemwibvsggnyfoabsfqxtgzecfiwpyqzsiilnrmugnbczsouczgfmkhunqfhpzqgyurrzpqccmvfjnbwgwrlclnvvsgbhkdfipnsinmasvryegdzuiazoisrcbgpyohvhvpujjxxtoruxpomxmjwuockcwjgpnhlfojvapaxnablqhujdtsofuiapfcjcdvxsavkavmrptqptpnxaasazuolwcltbysmezytwvmzislbasghogaqhhjqryzmbubsewcyustwguyiyvgswcefbpgrzjgvwezzmzfatatksonevbcupwtoxcjxaivqxciuklycbacoonuvvmuaazmrgguiuzyrhjbipwjpurofecklonpldgofikgijfiknaqisrmxfnvlqbwwifykjogtdqocdpffetagavwrchfiskwwecmrhhnpvlifaxkhbdapyafighonnxeamgpqnazvsnkbzrdcwyfyssseagfhlixn"), 's')
	fmt.Println(findTheDifference("", "y"), 'y')
	fmt.Println(findTheDifference("a", "ea"), 'e')
	fmt.Println(findTheDifference("ea", "aae"), 'a')
}
